### PR TITLE
iOS 13 support, GitHub Actions CI

### LINKED ISSUE #7: Incredible fork with full iOS 6-13 support, iPad Split View, Dark Mode!
I’d kill to get a binary or package of this!! 

https://github.com/SongXiaoXi/CocoaTop

### PR DESCRIPTION
**Pull request by Randomblock1**
SXX's fork adds full iOS 13 support, including support for the iPhone X screen, dark mode and split view on iPad.
My fork of SXX's fork adds GitHub Actions integration. It automatically compiles CocoaTop every time something is changed, and produces a .deb file as an artifact. Also fixes #7.

### CODE REVIEW

**Comment by Randomblock1** [comment]
Oh, and if you wouldn’t mind, tag this PR with ‘hacktoberfest-accepted’, I’m trying to participate in Hacktoberfest.

**Comment by badger200** [comment]
@Randomblock1 INCREDIBLE WORK!! I’ve been waiting years for this! 🤩🥳👏🏼👏🏼👏🏼👏🏼 @SongXiaoXi 

The iPad SlideOver and SplitView works flawlessly and is a dream come TRUE at last!

The install .deb needs work to seamlessly replace existing ru.domo.cocoatop64 installs though. 

1. I wonder if we would be better off retaining the existing bundle ID ru.domo.cocoatop64 ?  Because I have never seen an app switch bundle IDs without disastrous consequences. iCleaner just did this with v7.9.0 and it took me a ton of work on both my devices to get the dead app icon to work again. extrainst_ fails too etc. 

2. We should smoothly import existing settings, as it takes a long time to reselect and reorder all my columns from scratch. CocoaTop2.0.2+debug has a buggy preferences issue where it saves ru.domo.cocoatop64.plist to BOTH /var/mobile/Library/Preferences/ (I believe the correct location) AND /var/root/Library/Preferences/, despite the fact the root copy doesn’t seem to get updated. 

I tried manually copying my ru.domo.cocoatop64 to com.sxx.cocoatop.plist in Mobile Preferences and chown mobile:mobile yet for some reason the new CocoaTop ignores anything I do with the plist. This is a major problem because:

3. The oldest bug in CocoaTop still exists: “Ports” submenu (when tapping a process) freezes CocoaTop on both my devices:
iPhone 6S, 13.3, unc0ver 5.3.1
iPad Pro 9.7”, 12.4, unc0ver 4.3.1

But since the ProcMode=3 setting gets saved, the user is now locked out of ever entering a process, because it will try to open in Ports which freezes the app again. So there’s no possible way to escape and choose anything else like Open Files. 

Surprisingly, killall -9 CocoaTop and hand modifying the .plist to ProcMode=1 had zero effect (as described in # 2^). Somehow CocoaTop is always retaining its settings (seemingly as it should) but I’m baffled where it’s saving them, because changes to the mobile Prefs plist never effects the settings when you restart CocoaTop. 

I even did an lsof -p 1234 and a fs_usage -f pathname 1234 to try observing what file CocoaTop is modifying but found nothing except a peculiar call to a seemingly nonexistent /usr/bin/Info.plist (??).

Ultimately the only way I could fix it was to hack in with NSCake / Tanner’s FLEXible and open FLEX Menu > NSUserPreferences and set ProcMode from 3 to 1 there, which instantly fixed everything. 

4. If we DO decide to use the new bundle ID for some reason(I strongly recommend against it), we need to add these lines to DEBIAN/control:

Conflicts: ru.domo.cocoatop64
Replaces: ru.domo.cocoatop64

I did it myself and repacked a .deb and it did successfully replace CocoaTop 2.0.2 but failed to remove the original icon. (Though I haven’t rebooted yet.)

- I also needed to run uicache. We should trigger this in the install. 

- I also found the post-install executable is “signed, but ‘unsigned’ per JTool2”. We should be triggering an ldid call like the vast majority of tweaks do. 

I will submit a pull with my DEBIAN/control conflict changes for now but that’s just a temporary workaround until we can get the deb to seamlessly replace existing CocoaTop installs.

**Comment by Randomblock1** [comment]
@D0m0 We should probably change the bundle ID back to 64. Also, you should put this onto BigBoss. It's a lot easier for the average user to search "cocoatop" than it is for them to find the artifact in the GitHub Actions. Should be a separate package since the bundle ID is different.

Also, the way I fixed getting stuck in Ports was to go to Settings tab and hit Reset. Still a bug though.
UIcache is done by most package managers and even code injection systems. It just doesn't happen with dpkg.
I don't really see a reason to ldid sign the executable, it seems to work just fine without it.

**Comment by badger200** [comment]
@Randomblock1 Ah you are correct, I forgot I installed a @CydiaGeek (or @julioverne?) tweak that makes Cydia uicache manual (to make Cydia faster.) My bad. 

I know it works unsigned, but there’s an issue with my iOS 12.4 unc0ver 4.3.1 iPad Pro using MobileSubstrate (latest 7111) where intermittently, unsigned apps will fail with “Killed: 9” which causes all sorts of confusing as hell issues if you’re not at the Terminal and not aware of this. 

I’ve gone to every length trying to track down the root cause of this for at least 6 months and I am still empty handed. I didn’t have this problem for the 2 years prior. 

I suspect it’s either an unc0ver or MobileSubstrate bug, as the dmesg error when it happens is always something like “AMFI: code is completely unsigned, no CS blob? Must be at least ad-hoc signed.”

I can almost always solve this by running an ldid signing command (from memory so don’t quote me on this:) 
ldid -K/usr/share/entitlements/global.xml -M/usr/share/jailbreak/signcert.p12 binaryname

Either way, I believe signing the binary is the “proper” thing to do.

**Comment by D0m0** [comment]
All right, I'll put it on BigBoss.

So, which bundle id do we use? ru.domo.cocoatop64?

**Comment by Randomblock1** [comment]
We got 2 choices.
1. ru.domo.cocoatop appears as an update to existing installs of CocoaTop who installed it through BigBoss, but legacy users won't be able to use it (I think.)
2. ru.domo.cocoatop64 appears as an update to newer dpkg/Filza installs of the beta CocoaTop deb, but it has to be resubmitted to BigBoss and you have to create a new depiction for it. It will appear as a separate package to the above option, so legacy users won't even notice. You would have to set the name to CocoaTop (64-bit) to differentiate it from the previous one.

I vote for option 2. Also, you should address #9 before submitting it to BB, since that will affect the preferences. Otherwise, it's just some control file changes and it's ready to go.

**Comment by badger200** [comment]
I forgot there are 2 existing bundle IDs:

ru.domo.cocoatop v2.0.1 on Bigboss
- Cydia description states support up to iOS 10. Last updated July 2017. 
- Presumably, there aren’t any current users using this on iOS 13, 14, and possibly 12(?) as I think it flat out didn’t function(?)

ru.domo.cocoatop64 v2.0.2-1+debug I obtained from NotMyTweaks.github.io repo.
- Presumably, this is the one with the most active current users. 

Ideal solution would be to update bigboss to current, change bigboss claimed bundle ID to cocoatop64, and add to DEBIAN/control:

Replaces: ru.domo.cocoatop
Conflicts: ru.domo.cocoatop

(I’m just copying and pasting from a similar tweak, but I’m assuming both lines are necessary(?))

This upgrades the maximum number of users, while limiting bundle ID-change-related-bugs to the small group on old iOS. (We should still try to make it install correctly, might have to prompt user to reboot to get rid of original CocoaTop app icon. I had 2 identical app icons, until a respiring I think.)

Finally, whoever runs NotMyTweaks.github.io - it’d be nice if we coordinate with them somehow. I am guessing most people got CocoaTop64 from the same Reddit r/jailbreak post I did.

**Comment by Randomblock1** [comment]
Yes, we would have to add that to the control file so upgrading is easy.

The original 64-bit deb was from https://d0m0.github.io, so I don't think we need to do anything related to the mirror repo. Adding this to BigBoss will automatically make an upgrade appear.

The extra icons left over disappear when you run a UICache. Every package manager does this automatically, but dpkg doesn't (for obvious reasons). We don't need to do anything about that, especially since people are going to download it only through the repo.

**Comment by badger200** [comment]
BTW I’ve gotta thank you all again, @Randomblock1 @D0m0 and especially our hero @SongXiaoXi , because this iPad SlideOver and Split View is a real game-changer! I’ve had a few days to use it. 

The stuff this allows me to diagnose now with a single screen, on-device is incredible. So many scenarios where an app is misbehaving, now I can observe things like processes’ top CPU%, Mem, Files Opened, active Threads, Disk R/W Rate, etc in real-time as I’m witnessing it occur!

Btw, none of the network columns have ever functioned for me on any device since I started jailbreaking 3y ago on iOS 10.2. Has anyone ever seen Net Bytes Tx/Rx Delta function? 

We should really conditionally disable any functions known-invalid per-iOS version.

**Comment by badger200** [comment]
@D0m0 Any update on compiling/publishing the update to BigBoss?

**Pull request merged**
